<<<<<<< HEAD
on: 
    push:
        branches: [master]
    

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - run: node --version
            - run: npm --version
            - uses: actions/checkout@v4
            
            
            - name: Log in to Docker Hub
              run: |
                echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
                docker image build -t arpithak06/dataphion:tagname .
                docker push arpithak06/dataphion:tagname
=======

>>>>>>> 11f42cc5ae48af9db933b5347475e5b8eaaf5ef1
